### ISSUE TITLE
README

### ISSUE THREAD

**Issue by dzhlobo** [alexeypato/personal-budget-app#9]
@alexeypato, давай добавим в репозиторий файл README, в котором будет описано:
1. Как установить и запустить приложение у себя локально (какие команды выполнять).
2. Как запускать тесты.

И вообще, все, что посчитаешь нужным рассказать.

**Comment by alexeypato** [comment]
@Proghat README добавил, с тестами пока не разобрался поэтому их нету.

**Comment by dzhlobo** [comment]
@alexeypato, понял 👍 .

Закрывай ишью когда сделал задание ;-).
